.github/workflows/tests.yml

With this pull request, I aimed to fix the failing integration tests due to a missing Aspell installation on the action worker. 
As you can see from the commit history, installing it on Windows proves rather challenging...
As you can see from the website [http://aspell.net/](http://aspell.net/) they no longer provide a Windows port, but you can use it through MSYS2. In this pull request I managed to install the legacy Windows port. 
The only problem with this is that the other OS install **Aspell 0.60.8** and the legacy Windows Port uses **Aspell 0.50.3**.
This results in the Testsuite failing, as the suggestions seem to be different in the older language set...
**At this point I am open to feedback on how we should continue: I see the following options:**
1. Mock the Aspell …

[CI] Fix integration tests (Feedback Welcome)

---

src/Checkers/ClassChecker.php

This PR only rename a parameter on `ClassChecker's` `getErrorLine` method, to be more clear what this parameter is, and ensure the checker only check for php files

feat: little tweaks on ClassChecker

---

src/Checkers/FileSystemChecker.php

The [Symfony docs](https://symfony.com/doc/current/components/finder.html#version-control-files) for the Finder component says that VCS files are ignored by default.
Pest still passes with the line removed

Remove ignoreVcs in Finder::check() (tests still pass)

---

src/Checkers/ClassChecker.php

This pull request extends the class checker by a new method to also check class constants and their values.
However event with mistakes like `public const CONSTANT_WITH_TYPO_ERORR = 2;` the checks pass.
This is because snake case is not handled. I added a new parser in #34 which solves this problem!
Therefore I couldn't write effective tests for this feature. Once the Parser is accepted, this can be extend by tests.
- #34 
Required to actually write tests for this feature

Extend ClassChecker to check PHP Constants

---

src/Console/Commands/CheckCommand.php

This PR calculates (naively) the column for each mispelling, and adds it to the output of each Issue:
- the <a> href and text  has the column now
- below the "ISSUE" line now we show the full line, and below that, there's an arrow pointing up at the character where the misspelling occurred

feat: show full line and column position of misspellings on output

---

README.md

This adds a section to the README titled "Command Option" - see below.

Add Command Option to README

---

peck.json
src/Checkers/ClassChecker.php
src/Checkers/FileSystemChecker.php
src/Support/SpellcheckFormatter.php
tests/Unit/ConfigTest.php
tests/Unit/Support/SpellcheckFormatterTest.php

As suggested on stream, I changed the name of the class (and function as well).
#34

[Formatter] Rename NameParser to SpellcheckFormatter

---

src/Services/Spellcheckers/InMemorySpellchecker.php

When coding we don't want to have suggestions like `checker's` but only `checkers`.
I did not add test, as I want to wait for some more pull requests to get merged, before I get a lot of conflicts.
**Before and After:**

[Suggestions] Filter the suggestions to not show words with apostrophes

---

src/Console/Commands/CheckCommand.php
src/Plugins/Cache.php
tests/.pest/snapshots/Console/OutputTest/it_may_fail.snap
tests/Integration/CheckCommandTest.php
tests/Unit/Plugins/CacheTest.php

- Removed the exception from the getIssueColumn() method, as it seems unlikely for $column to ever be false in the current flow, making it difficult to test without mocking.
- What are our thoughts on this? Is there a specific reason for throwing an exception in this case, rather than handling the value more appropriately? For example, if the result is 0, we could simply avoid rendering. However, based on the current implementation, it's hard to see how this scenario could occur.
- Made a minor update to the cache file logic to correctly handle the serialized false boolean (which is valid) and to return null when the serialized contents are an empty string.
- Added tests to ensure 100% test coverage.

fix: 100% coverage

---

src/Checkers/ClassChecker.php
src/Checkers/FileSystemChecker.php
src/Support/NameParser.php

Redo of https://github.com/peckphp/peck/pull/53 with only the redundant code parts.
- removed `array_values` at the end of return; is redundant unless `usort` introduces gaps in the array keys, which I don't believe it does. In which case we can directly return $issues after sorting
- extra assignment of `$name` combined into a single line
- updated NameParser::parse to return with `strtolower` to remove unnecessary assignments (without affecting readability)

refactor: remove redundant code / unnecessary variable assignments

---

README.md

Make Composer Install Instructions Clearer by including the `--dev` flag in the composer install command.

docs: add --dev flag to composer install

---

src/Console/Commands/CheckCommand.php
tests/.pest/snapshots/Console/OutputTest/it_may_fail.snap
tests/.pest/snapshots/Console/OutputTest/it_may_pass.snap
tests/Console/OutputTest.php

This PR aims to add the execution duration of the peck

feat: show execution duration

---

peck.json
src/Checkers/SourceCodeChecker.php
src/Kernel.php
tests/.pest/snapshots/Console/OutputTest/it_may_fail.snap
tests/Fixtures/ClassesToTest/ClassWithTypoErrors.php
tests/Fixtures/ClassesToTest/InterfaceWithSpellingMistake.php
tests/Fixtures/ClassesToTest/TraitWithTypo.php
tests/Fixtures/EnumsToTest/BackendEnumWithTypoErrors.php
tests/Fixtures/EnumsToTest/FolderThatShouldBeIgnored/EnumWithTypoErrors.php
tests/Fixtures/EnumsToTest/UnitEnumWithTypoErrors.php
tests/Unit/Checkers/FileSystemCheckerTest.php
tests/Unit/Checkers/SourceCodeCheckerTest.php
tests/Unit/ConfigTest.php
tests/Unit/KernelTest.php

**This pull request adds full support for Enums, Traits and Interfaces!**
> Before creating a second pull request for the same feature, please try to give feedback here. Maybe we can simply add your suggestions or refactorings in this request instead of going through the same struggle as initially with the checkers
While working on this pull request, I found out that we already support Interfaces and Traits because ReflectionClass can be used for Interfaces as well!
Therefore, I simply added a complete test-suite for these type definitions!
**Edit:** The Test are currently failing, because I merged the main branch into this to resolve conflicts which then brought the new console check which at this point still has the problem with the line width. The other test previously passed!
```php …
```

[Checker]: Add Support for Interfaces, Traits and Enums (ClassChecker -> SourceCodeChecker) (New #49)

---

src/Services/Spellcheckers/Aspell.php

Fixes the bug when changing the allowed words through the configuration file and keeps the cache.
Now the filtering of words is done after executing the command, or recovering an old execution from the cache. So even if the configuration file is changed, the cache will still be valid to be used with a new configuration.
https://github.com/peckphp/peck/issues/76

fix(misspelling-whitelist-filter): fix misspelling whitelisted words when getting it from cache

---

composer.json
src/Checkers/SourceCodeChecker.php
tests/.pest/snapshots/Console/OutputTest/it_may_fail.snap
tests/Fixtures/ParentAndTraits/ChildClass.php
tests/Fixtures/ParentAndTraits/ParentClass.php
tests/Fixtures/ParentAndTraits/UsedTrait.php
tests/Unit/Checkers/SourceCodeCheckerTest.php
tests/Unit/KernelTest.php

Redo of #70 
Now, checking that methods, properties and constants are not coming from traits too.
> Source Code checker was inspecting methods, properties, etc., in extended classes and traits. So it was reporting typos also in libraries, not only in the code of the project. 
> 
> Since it was not possible to find the typo in the current class, it was also reporting the misspelling with 0 (zero) value in the `line` property, which breaks the command output in `CheckCommand` [here](https://github.com/peckphp/peck/blob/77c282b5eb504f1cb0ddfb79fb67589a489483e7/src/Console/Commands/CheckCommand.php#L218).
> 
https://github.com/peckphp/peck/issues/72
https://github.com/peckphp/peck/pull/70

fix: checking code in extended class and traits

---

src/Services/Spellcheckers/Aspell.php
src/Support/SpellcheckFormatter.php
tests/Unit/Support/SpellcheckFormatterTest.php

As discussed in issue #65 and PRs #66 and #71, this PR adds more regex to split up words if there are abbreviations (e.g., [`getCountriesFromUSAAndEU`] will be split into [`get countries from usa and eu`]).
Since we enforce everything to be lowercase, I have also added [`--ignore-case`] to Aspell, as mentioned by @c0nst4ntin in a [comment](https://github.com/peckphp/peck/issues/65#issuecomment-2585381860) on #65.
Before
After
It also have a test to check that it splits it up correctly
Issue #65 False positives for abbreviations (e.g., 'USA', 'EU') due to forced lowercase in spell-check 
PR #66 Fix(NameParser): Handle abbreviations
PR #71 Fix(SpellcheckFormatter): Handle abbreviations

Fix(SpellcheckFormatter): Handle abbreviations - Resolves #65

---

composer.json

When installing peck with the current Symfony LTS version (6.4) composer runs into a problem with the console component.
Overview: [Symfony Versions](https://symfony.com/releases)
Not supporting the previous LTS ([which has received extended support until 2029](https://symfony.com/blog/symfony-5-4-lts-will-receive-security-fixes-until-february-2029-thanks-to-ibexa)) is okay for now. But we should at least support the current LTS
- #83

Support Symfony 6.4 (LTS)

---

src/Checkers/FileSystemChecker.php
src/Checkers/SourceCodeChecker.php

Symfony Finder already provides a method to sort files. We don't need to implement our own.

refactor: sort files with finder

---

stubs/presets/base.stub
stubs/presets/laravel.stub

I added the following terms to the base preset:
- `accessor`
- `backtrace`
- `nullable`
- `serializer`
And these to the laravel preset:
- `chaperone` (laravel model relation method)
- `jetstream` (first party laravel package)
- `typesense` (laravel scout integration)
I am happy to move the laravel ones into the base preset, but I consider at least `jetstream` and `typesense` to be more laravel-specific.
I know there is a pending PR for alphabetical sorting of the terms, but to prevent confusion, I added mine to the end of the files.

Added more terms to the base and laravel presets

---

src/Support/SpellcheckFormatter.php
tests/Unit/Support/SpellcheckFormatterTest.php

Found a bug where SpellcheckFormatter was not formatting correctly a phpdoc comments.
Fixed by adding a regex to remove special characters like `\ / < > * @ $` in the SpellcheckFormatter.

fix: phpdoc special characters

---

README.md

Aspell is installed only in Linux and macOS, so before executing Peck you must check that it is running in one of those OS's.

Update README.md for CI actions: check OS before running Peck, otherwise actions will fail if Aspell is not installed in that OS

---

src/Checkers/SourceCodeChecker.php

Remove array flattening that is not necessary since 4f81fc4b887c9f7caa9033b3b57fa50957185c53.
Also, checking if the constant was declared in parent class is cheaper and can fail more frequently than checking if it was declared in traits. So we should check that first.

refactor: getConstantNames remove useless array flattening and improve filter order

---

src/Console/Commands/CheckCommand.php

White text in green/blue background is usually hard to read in most terminal color schemes.
Pint, pest and all other tools use black text in green background, so we can follow the pattern.

fix: output colors hard to read

---

.github/workflows/formats.yml
.github/workflows/tests.yml
composer.json
src/Config.php
src/Plugins/Cache.php
src/Support/PresetProvider.php

This PR attempts to reduce the minimum supported php version to 8.2, to keep in step with Laravel's php support.
This would close  issue #133

Set minimum php version to 8.2

---

README.md
src/Config.php
src/Services/Spellcheckers/Aspell.php
tests/Unit/ConfigTest.php

Adding a new setting to the config, that lets you configure the language passed to the underlying aspell command

[Config]: Adding "language" as a setting

---

src/Console/Commands/CheckCommand.php
src/Services/Spellcheckers/Aspell.php
tests/Console/OutputTest.php
tests/Unit/Services/AspellTest.php

This pull request handles the Aspell response so that misspellings without a suggestion are also marked as a misspelling.
I also adjusted the output accordingly and added testing.
- #100

[Aspell]: Handle misspellings with no Suggestions
